// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloudPrototyper.NET.Framework.v462.Common.Templates.DataLayerTemplates.AzureSql
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class AzureSqlDatabaseContextTemplate : AzureSqlDatabaseContextTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data.Entity;\r\nusin" +
                    "g System.Linq;\r\n// Azure sql database\r\nnamespace ");
            
            #line 12 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));
            
            #line default
            #line hidden
            this.Write(" \r\n{\r\n    public class ");
            
            #line 14 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" : DbContext, ");
            
            #line 14 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StorageInterface.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 14 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StorageInterface.Name));
            
            #line default
            #line hidden
            this.Write(@"
    {
		private static readonly Random Random = new Random();
		private readonly Dictionary<Type, object> _dbSets = new Dictionary<Type, object>();
		private readonly Dictionary<string, Tuple<Type,int>> _names = new Dictionary<string, Tuple<Type,int>>();
		public const string Name = """);
            
            #line 19 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelParameters.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n\t\tstatic ");
            
            #line 21 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n\t\t\tDatabase.SetInitializer<");
            
            #line 23 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 23 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(">(null);        \r\n\t\t} \r\n\r\n\t\tpublic ");
            
            #line 26 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("() : base(\"");
            
            #line 26 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ModelParameters.ConnectionString));
            
            #line default
            #line hidden
            this.Write("\") \r\n\t\t{ \r\n\r\n\t\t\tDatabase.SetInitializer<");
            
            #line 29 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 29 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(">(new CreateDatabaseIfNotExists<");
            
            #line 29 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 29 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(">());\r\n            Configuration.AutoDetectChangesEnabled = false;\r\n\t\t\tInitDbSetD" +
                    "ictionary();\r\n\t\t}\r\n\t\t\r\n        public string GetName()\r\n        {\r\n            r" +
                    "eturn \"");
            
            #line 36 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Key));
            
            #line default
            #line hidden
            this.Write("\";\r\n        }\r\n\t\t\r\n");
            
            #line 39 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic DbSet<");
            
            #line 40 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 40 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 40 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("s { get; set; }\r\n");
            
            #line 41 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic DbSet<T> GetDbSet<T>(Type entityType) where T : class, ");
            
            #line 43 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EntityInterface.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 43 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EntityInterface.Name));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            return _dbSets[typeof (T)] as DbSet<T>;\r\n        }\r\n\t\t\r\n" +
                    "\t\tpublic List<object> GetEntities(string entitySetName, string entityName, ");
            
            #line 48 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 48 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Query.Name));
            
            #line default
            #line hidden
            this.Write(" query)\n\t\t{\r\n\t\t\tif(query.IsNominal) \r\n\t\t\t{\r\n");
            
            #line 51 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif(entityName == \"");
            
            #line 52 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t\t{\r\n\t\t\t\t\tif(query.PropertyName == \"Id\")\r\n\t\t\t\t\t{   var parameter = int.Pars" +
                    "e(query.NominalParameter);\r\n\t\t\t\t\t\treturn ");
            
            #line 56 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Where(x=> x.Id == parameter).AsNoTracking().ToList().Cast<object>().ToList();\r\n" +
                    "\t\t\t\t\t}\r\n");
            
            #line 58 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var prop in entity.ModelParameters.Properties.Where(x=>x.Name != "Id")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tif(query.PropertyName == \"");
            
            #line 59 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("\") \r\n\t\t\t\t\t{\r\n\t\t\t\t\t\treturn ");
            
            #line 61 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Where(x=>string.Compare(x.");
            
            #line 61 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(".ToString(), query.NominalParameter, StringComparison.Ordinal) == 0).AsNoTracking" +
                    "().ToList().Cast<object>().ToList();\r\n\t\t\t\t\t}\r\n");
            
            #line 63 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\t \r\n");
            
            #line 65 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\telse \r\n\t\t\t{\r\n");
            
            #line 69 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\tif(entityName == \"");
            
            #line 70 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t\t{\r\n\t\t\t\t\tif(query.PropertyName == \"Id\")\r\n\t\t\t\t\t{\r\n\t\t\t\t\t    var minParameter" +
                    " = int.Parse(query.MinValue);\r\n\t\t\t\t\t    var maxParameter = int.Parse(query.MaxVa" +
                    "lue);\r\n\t\t\t\t\t\treturn ");
            
            #line 76 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Where(x=> x.Id >= minParameter && x.Id <= maxParameter).AsNoTracking().ToList()" +
                    ".Cast<object>().ToList();\r\n\t\t\t\t\t}\r\n");
            
            #line 78 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var prop in entity.ModelParameters.Properties.Where(x=>x.Name != "Id")) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tif(query.PropertyName == \"");
            
            #line 79 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write("\") \r\n\t\t\t\t\t{\r\n\t\t\t\t\t\treturn ");
            
            #line 81 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("s.Where(x=>string.Compare(x.");
            
            #line 81 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(".ToString(), query.MinValue, StringComparison.Ordinal) >= 0 && string.Compare(x.");
            
            #line 81 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prop.Name));
            
            #line default
            #line hidden
            this.Write(".ToString(), query.MaxValue, StringComparison.Ordinal) <= 0).AsNoTracking().ToLis" +
                    "t().Cast<object>().ToList();\r\n\t\t\t\t\t}\r\n");
            
            #line 83 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\t \r\n");
            
            #line 85 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"			} 

			return new List<object>();	
		}
		public void InsertAll(string entitySetName, string entityName, object[] toInsert)
		{
			Set(_names[entitySetName].Item1).AddRange(toInsert);
			SaveChanges();
		}
				
		
		public void Insert(string entitySetName,string entityName, int count)
		{
			object[] generated = null;
");
            
            #line 100 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tif(entityName == \"");
            
            #line 101 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t{\r\n\t\t\t\tgenerated = ");
            
            #line 103 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DataGenerator.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 103 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DataGenerator.Name));
            
            #line default
            #line hidden
            this.Write(".GetInstance().Generate<");
            
            #line 103 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 103 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write(">(count).ToArray();\r\n\t\t\t} \r\n");
            
            #line 105 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tInsertAll(entitySetName,entityName,generated);\n\r\n\t\t}\r\n\r\n\t\tprivate void InitDbS" +
                    "etDictionary()\r\n        {\r\n");
            
            #line 111 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t_dbSets.Add(typeof(");
            
            #line 112 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 112 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("), ");
            
            #line 112 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("s); \r\n");
            
            #line 113 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 114 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 foreach(var set in Model.ModelParameters.EntitySets) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t_names.Add(\"");
            
            #line 115 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(set.Name));
            
            #line default
            #line hidden
            this.Write("\", new Tuple<Type,int>(typeof(");
            
            #line 115 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Entities.Single(x=>x.Name == set.EntityName).Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 115 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Entities.Single(x=>x.Name == set.EntityName).Name));
            
            #line default
            #line hidden
            this.Write("),");
            
            #line 115 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(set.Count));
            
            #line default
            #line hidden
            this.Write("));\n");
            
            #line 115 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\DataLayerTemplates\AzureSql\AzureSqlDatabaseContextTemplate.tt"

private global::CloudPrototyper.NET.Framework.v462.Common.Generators.DataLayerGenerators.AzureSqlDatabase.AzureSqlDatabaseContextGenerator _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::CloudPrototyper.NET.Framework.v462.Common.Generators.DataLayerGenerators.AzureSqlDatabase.AzureSqlDatabaseContextGenerator Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::CloudPrototyper.NET.Framework.v462.Common.Generators.DataLayerGenerators.AzureSqlDatabase.AzureSqlDatabaseContextGenerator)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::CloudPrototyper.NET.Framework.v462.Common.Generators.DataLayerGenerators.AzureSqlDatabase.AzureSqlDatabaseContextGenerator)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class AzureSqlDatabaseContextTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
