// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloudPrototyper.NET.Framework.v462.Common.Templates.BusinessLayerTemplates.Services
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class HandlerTemplate : HandlerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using Microsoft.ServiceBus;
using Microsoft.ServiceBus.Messaging;
using Newtonsoft.Json;
using System;
using System.Diagnostics;
using System.IO;
using System.Threading;
using Castle.Windsor;
using System.Collections.Generic;
// Queue handler
namespace ");
            
            #line 17 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));
            
            #line default
            #line hidden
            this.Write(" \r\n{\r\n    public class ");
            
            #line 19 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 19 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusHandlerInterface.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 19 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusHandlerInterface.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n        private string connectionString;\r\n        private string queueName;" +
                    "\r\n\t\tpublic const string Name = \"");
            
            #line 23 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n        private QueueClient _client;\r\n        private ManualResetEvent comple" +
                    "tedEvent = new ManualResetEvent(false);\r\n\r\n");
            
            #line 27 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 foreach(var action in Model.Actions) { 
            
            #line default
            #line hidden
            this.Write("\n\t\tpublic ");
            
            #line 27 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 27 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\n");
            
            #line 27 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 28 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("(\n");
            
            #line 28 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 foreach(var action in Model.Actions) {  if(Model.Actions.Last().Equals(action)) {
            
            #line default
            #line hidden
            this.Write("\n\t\t");
            
            #line 28 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 28 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 28 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("\n");
            
            #line 28 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 29 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Namespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 29 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 29 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 30 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 }} 
            
            #line default
            #line hidden
            this.Write("\t\t) \r\n\t\t{\r\n");
            
            #line 33 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 foreach(var action in Model.Actions) { 
            
            #line default
            #line hidden
            this.Write("\n\t\t\tthis.");
            
            #line 33 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 33 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(action.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(";\n");
            
            #line 33 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            this.connectionString = \"");
            
            #line 34 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AzureServiceBusQueue.ConnectionString));
            
            #line default
            #line hidden
            this.Write("\";\r\n            this.queueName = \"");
            
            #line 35 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AzureServiceBusQueue.Name));
            
            #line default
            #line hidden
            this.Write(@""";
        }

        public void OnStart()
        {
        
            // Initialize the connection to Service Bus Queue
            _client = QueueClient.CreateFromConnectionString(connectionString);
            _client.RetryPolicy = new RetryExponential(TimeSpan.FromSeconds(0.3), TimeSpan.FromSeconds(2), 5);
            //Client.PrefetchCount = 4;
        }

        public void Run()
        {
            Trace.WriteLine(""Starting processing of messages"");

            // Initiates the message pump and callback is invoked for each message that is received, calling close on the client will stop the pump.
            _client.OnMessage((receivedMessage) =>
            {
                // Get DateTime when task processing began
                DateTime startedAt = DateTime.Now;

                try
                {

                    using (StreamReader sr = new StreamReader(receivedMessage.GetBody<System.IO.Stream>()))
                    {
                        using (JsonTextReader jr = new JsonTextReader(sr))
                        {

                            JsonSerializer serializer = new JsonSerializer();
                            var messageBody = serializer.Deserialize(jr);
");
            
            #line 67 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 foreach(var action in Model.ModelParameters) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tif(receivedMessage.Label == \"");
            
            #line 68 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((action.Trigger as CloudPrototyper.Model.Applications.MessageReceivedTrigger).MessageType));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t{\r\n\t\t\t\t ");
            
            #line 70 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Actions.FirstOrDefault(x=>x.Key.Equals(action.Name)).Name));
            
            #line default
            #line hidden
            this.Write(".Execute(new List<string>());\r\n\t\t\t} \r\n");
            
            #line 72 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"							  Trace.WriteLine(""Processing of message completed "" + receivedMessage.Label);
                        }
                    }
                }
                catch (Exception ex)
                {
                    Trace.WriteLine(""Failed processing of message "" + receivedMessage.Label);
                }
            }, new OnMessageOptions() { MaxConcurrentCalls = 1 });

            completedEvent.WaitOne();
        }
    }
}
");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\ogasi_000\Documents\Visual Studio 2015\Projects\Prototyper\CloudPrototyper\CloudPrototyper.NET.Framework.v462.Common\Templates\BusinessLayerTemplates\Services\HandlerTemplate.tt"

private global::CloudPrototyper.NET.Framework.v462.Common.Generators.BusinessLayerGenerators.Services.HandlerGenerator _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::CloudPrototyper.NET.Framework.v462.Common.Generators.BusinessLayerGenerators.Services.HandlerGenerator Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::CloudPrototyper.NET.Framework.v462.Common.Generators.BusinessLayerGenerators.Services.HandlerGenerator)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::CloudPrototyper.NET.Framework.v462.Common.Generators.BusinessLayerGenerators.Services.HandlerGenerator)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class HandlerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
